version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-north-1
    IMAGE_REPO_NAME: testritik
    ACCOUNT_ID: 855735869574
    EC2_HOST: 13.60.40.253

phases:
  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Setting up SSH key..."
      - echo "$PRIVATE_KEY_B64" | base64 -d > key.pem
      - chmod 400 key.pem

      # DEBUG (remove later)
      - echo "Checking key format..."
      - head -n 2 key.pem

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME .

      - echo "Tagging Docker image..."
      - docker tag $IMAGE_REPO_NAME:latest $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

      - echo "Deploying to EC2..."

      - ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_HOST "
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com &&
          docker pull $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest &&
          docker stop app || true &&
          docker rm app || true &&
          docker run -d -p 80:5000 --name app $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
        "
